Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
import numpy as np

#create an array
arr = np.array([1,2,3,4,5])
print(arr)

#add 2 to each element
add = arr+2
print(add)

#multiply 3 with each  element
mul = arr*3
print(mul)

#divide each element by 2
div = arr/2
print(div)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])



In [1]:
import numpy as np

#reverse array
arr = np.array([1,2,3,6,4,5])
arr = arr[::-1]
print(arr)

#most frequent value
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(x).argmax(), np.bincount(y).argmax())

[5 4 6 3 2 1]
1 1


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column


In [ ]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

#1st row, 2nd col
print(arr[0][1])

#3rd row, 1st col
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np

#create an array
naman = np.linspace(10,100,25)
print("Array:")
print(naman)

#dimensions of array
print("dimensions of array are ", naman.ndim)

#shape of array
print("shape of array is ", naman.shape)

#total number of elements in array
print("total number of elements in array are ", naman.size)

#data type of each element
print("Data type of each element is ", naman.dtype)

#number of bytes consumed by array
print("number of bytes consumed by each array is ", naman.nbytes)

#transpose using reshape
print("Transpose using reshape:")
print(naman.reshape(1,-1))

#transpose using .T
print("Transpose using .T:")
print(naman.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions of array are  1
shape of array is  (25,)
total number of elements in array are  25
Data type of each element is  float64
number of bytes consumed by each array is  200
Transpose using reshape:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using .T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>

In [2]:
import numpy as np

#create a 2D array
ucs420_naman = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Array:")
print(ucs420_naman)

#mean
print("Mean = ",np.mean(ucs420_naman))

#median
print("Median = ",np.median(ucs420_naman))

#max
print("Max = ",np.max(ucs420_naman))

#min
print("Min = ",np.min(ucs420_naman))

#unique elements
print("Unique elements are ",np.unique(ucs420_naman))

#reshape into 4 rows and 3 cols
reshaped_ucs420_naman = ucs420_naman.reshape(4,3)
print(reshaped_ucs420_naman)

#resize into 2 rows and 3 cols
resized_ucs420_naman = np.resize(ucs420_naman,(2,3))
print(resized_ucs420_naman)

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean =  43.333333333333336
Median =  37.5
Max =  90
Min =  10
Unique elements are  [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
